// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("JsonSchemaProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("JsonSchemaProvider")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-10-16T00:00:00.0000000+02:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","pre")>]
[<assembly: AssemblyMetadataAttribute("GitHash","03b8fca22ec8b7ea48427c8d646f75a008b90636")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "JsonSchemaProvider.Runtime"
    let [<Literal>] AssemblyProduct = "JsonSchemaProvider"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-10-16T00:00:00.0000000+02:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "pre"
    let [<Literal>] AssemblyMetadata_GitHash = "03b8fca22ec8b7ea48427c8d646f75a008b90636"
