// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("JsonSchemaProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("JsonSchemaProvider")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2023-10-17T00:00:00.0000000+02:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","pre")>]
[<assembly: AssemblyMetadataAttribute("GitHash","dbdb9e586f02092e6b25f614b0bb9a7c0fdf88ba")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "JsonSchemaProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "JsonSchemaProvider"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2023-10-17T00:00:00.0000000+02:00"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyInformationalVersion = "0.1.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "pre"
    let [<Literal>] AssemblyMetadata_GitHash = "dbdb9e586f02092e6b25f614b0bb9a7c0fdf88ba"
