name: .NET Publish

on:
  push:
    tags:
      - "*"

env:
  CONFIGURATION: Release

jobs:
  build:
    # Sets permissions of the GITHUB_TOKEN to allow release creating
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.x

      - name: Publish
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FAKE_DETAILED_ERRORS: true
          ENABLE_COVERAGE: false # AltCover doesn't work with Release builds, reports lower coverage than actual
        run: |
          ./build.sh Publish
